import smtplib
import ssl
from email.mime.text import MIMEText
from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import openpyxl
import imghdr
# provide path of the Excel sheet you want to read data from.
obj = openpyxl.load_workbook('')
sheet = obj.active

row_count = sheet.max_row
subject = " "  # add subject
sender = " "  # add sender email id
password = " "  # add password key generated by gmail

try:
    for i in range(1, row_count):
        receiver = sheet.cell(i + 1, 8).value
        # add your the row number and column number from Excel sheet in sheet.cell(row no. , column no.)
        message = MIMEMultipart()
        message["From"] = sender
        message["To"] = receiver
        message["Subject"] = subject
        text = """\
    <html>
        
        <body>
        <h2> Hi! </h2>
        <p>
        Add your content here 
        </p>
        </body>
    </html>
    """
        message.attach(MIMEText(text, "html"))
        file = "certificates/" + sheet.cell(i + 1, 6).value + ".jpg"
        print(file)

        with open(file, "rb") as attachment:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(attachment.read())
        encoders.encode_base64(part)
        part.add_header(
            "Content-Disposition",
            f"attachment; filename= {file}",
        )
        message.attach(part)
        text = message.as_string()

        # message.add_attachment(image_data, maintype='image', subtype=image_type, filename=image_name)
        context = ssl.create_default_context()
        try:
            with smtplib.SMTP_SSL('smtp.gmail.com', 465, context=context) as server:
                server.login(sender, password)
                server.sendmail(sender, receiver, text)
            print(receiver, "succesful")
        except Exception as e:
            print("not found")

except Exception as e:
    print("failed")
